

# Numbers

### List Phones

GET  {{host}}/api/numbers
Content-Type: application/json

### List Online Phones

GET  {{host}}/api/numbers/online
Content-Type: application/json

### Create a Phone Number
### 17207277520 / 12096777520 / 18037951555

POST {{host}}/api/numbers
Content-Type: application/json

{
  "phoneNumber": 18037951555,
  "countryCode": 1,
  "operator": 320260,
  "description": "",
  "rent": 0
}

### Phone Number Online Report

POST {{host}}/api/numbers/12096777520/online
Content-Type: application/json

{
  "number": 12096777520
}

### Delete a Phone Number

DELETE {{host}}/api/numbers/12096777520
Content-Type: application/json

###

POST {{host}}/api/numbers/18037951555/online
Content-Type: application/json

{
  "reportedAt": "2023-12-01T08:02:07.022Z",
  "from": "12096777520"
}