

# Numbers

### List Phones

GET  {{host}}/numbers
Content-Type: application/json

### Create a Phone Number
### 17207277520 / 12096777520

POST {{host}}/numbers
Content-Type: application/json

{
  "phoneNumber": 12096777520,
  "countryCode": 1,
  "operator": 320260,
  "description": "",
  "rent": 0
}

### Phone Number Online Report

POST {{host}}/numbers/12096777520/online
Content-Type: application/json

{
  "number": 12096777520
}

### Delete a Phone Number

DELETE {{host}}/numbers/12096777520
Content-Type: application/json
