

# Numbers

### List Phones

GET  {{host}}/numbers
Content-Type: application/json

### Add a Phone Number

POST {{host}}/numbers/add
Content-Type: application/json

{
  "number": "+12096777520",
  "countryCode": 1,
  "operator": 320260,
  "description": "",
  "rent": 0
}

### Delete a Phone Number

DELETE {{host}}/numbers/remove?
  phoneNumber=+2096777520
Content-Type: application/json
